services:
  - type: web
    name: sentiment-platform-backend
    env: python
    region: oregon
    buildCommand: ./.render/build.sh
    startCommand: gunicorn sentiment_backend.integrated_server:app -b 0.0.0.0:$PORT
    plan: free
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: ${SECRET_KEY}  # Set this in Render dashboard (DO NOT hardcode it)

    buildFilter:
      paths:
        - sentiment_backend/**
        - sentiment_dashboard/**
        - .render/build.sh
        - render.yaml

    build:
      cwd: sentiment_backend
